/**
 * İnverter Sistemleri kategorisi ve Off-Grid / Hibrit inverter ürünlerini ekler.
 * Kullanım: npx tsx prisma/seed-inverters.ts
 */

import { PrismaClient, Lifecycle } from '@prisma/client'

const prisma = new PrismaClient()

const inverterProducts: Array<{
  slug: string
  name: string
  nameEn: string
  brand: string
  mpn: string
  variantSku: string
  price: number
  subCategory: 'offgrid' | 'monofaze_hibrit' | 'trifaze_hibrit'
  specs: Record<string, unknown>
  description: string
  descriptionEn: string
  fullDescription: string
  fullDescriptionEn: string
}> = [
  // ----- Off-Grid -----
  {
    slug: 'orbit-6.2kw-offgrid-paralel',
    name: 'ORBİT 6.2 KW Tam Sinüs Off-Grid İnverter (12 Cihaz Paralellenebilir)',
    nameEn: 'ORBİT 6.2 kW Pure Sine Off-Grid Inverter (Up to 12 Units in Parallel)',
    brand: 'ORBİT',
    mpn: 'M6200-48PL',
    variantSku: 'M6200-48PL',
    price: 566.66,
    subCategory: 'offgrid',
    specs: {
      power_kw: 6.2,
      wave: 'Pure Sine Wave',
      power_factor: 1.0,
      pv_max_vdc: 500,
      mppt_a: 120,
      battery_voltage_v: '48V nominal',
      parallel_units: 12,
      modes: 'UTL, SOL, SBU, SUB',
      lifepo4: true,
      battery_optional: true,
      eq_function: true,
      wifi_dongle: true,
      communication: 'WiFi (optional remote monitoring)',
    },
    description: '6.2 kW Tam Sinüs Off-Grid, 500VDC PV, 120A MPPT. 12 cihaza kadar paralel. LiFePO4 uyumlu, aküsüz çalışabilir. WiFi dongle.',
    descriptionEn: '6.2 kW Pure Sine Off-Grid, 500VDC PV, 120A MPPT. Up to 12 units parallel. LiFePO4 compatible, can run without battery. WiFi dongle.',
    fullDescription: 'ORBİT 6.2 KW Tam Sinüs Off-Grid İnverter. Dalga: Tam Sinüs (Pure Sine Wave), Güç Faktörü 1.0. Maksimum 500 VDC PV girişi, 120A dahili MPPT şarj kontrol. LiFePO4 aküler ile tam uyumlu; akü olmadan da çalışabilir. UTL, SOL, SBU, SUB çıkış önceliği modları. EQ (Ekolayzer) fonksiyonu. Tek faz veya üç fazda toplam 12 cihaza kadar paralel. Tak-çalıştır WiFi dongle, opsiyonel uzaktan izleme. Çıkarılabilir toz koruma kapağı.',
    fullDescriptionEn: 'ORBİT 6.2 kW Pure Sine Off-Grid Inverter. 500VDC PV max, 120A built-in MPPT. LiFePO4 compatible, battery optional. UTL/SOL/SBU/SUB modes. EQ function. Up to 12 units in parallel. WiFi dongle, optional remote monitoring.',
  },
  {
    slug: 'orbit-6.2kw-offgrid-standart',
    name: 'ORBİT 6.2 KW Tam Sinüs Off-Grid İnverter (Paralel Olmayan Standart Model)',
    nameEn: 'ORBİT 6.2 kW Pure Sine Off-Grid Inverter (Standard, No Parallel)',
    brand: 'ORBİT',
    mpn: 'M6200-48',
    variantSku: 'M6200-48',
    price: 506.72,
    subCategory: 'offgrid',
    specs: {
      power_kw: 6.2,
      wave: 'Pure Sine Wave',
      power_factor: 1.0,
      pv_max_vdc: 500,
      mppt_a: 120,
      parallel: false,
      modes: 'UTL, SOL, SBU, SUB',
      lifepo4: true,
      battery_optional: true,
      eq_function: true,
      wifi_dongle: true,
    },
    description: '6.2 kW Tam Sinüs Off-Grid, 500VDC PV, 120A MPPT. Paralelleme yok. LiFePO4 uyumlu, aküsüz çalışabilir.',
    descriptionEn: '6.2 kW Pure Sine Off-Grid, 500VDC PV, 120A MPPT. No parallel. LiFePO4 compatible, battery optional.',
    fullDescription: 'ORBİT 6.2 KW Tam Sinüs Off-Grid İnverter (standart model). Tam Sinüs dalga, Güç Faktörü 1.0. Maks 500 VDC PV, 120A dahili MPPT. LiFePO4 uyumlu, aküsüz çalışabilir. UTL/SOL/SBU/SUB modları, EQ fonksiyonu. WiFi dongle, toz koruma kapağı. Bu model paralelleme desteklemez.',
    fullDescriptionEn: 'ORBİT 6.2 kW Pure Sine Off-Grid Inverter (standard). 500VDC PV, 120A MPPT. LiFePO4 compatible. No parallel support.',
  },
  {
    slug: 'srp-5kw-offgrid-monofaze-lv',
    name: 'SRP 05 KW Monofaze Off-Grid İnverter - Düşük Voltaj (LV)',
    nameEn: 'SRP 5 kW Single-Phase Off-Grid Inverter - Low Voltage (LV)',
    brand: 'SRP',
    mpn: 'OFFGRİD-5KRS-F1-MF-LV',
    variantSku: 'OFFGRID-5KRS-F1-MF-LV',
    price: 584.65,
    subCategory: 'offgrid',
    specs: {
      power_kw: 5,
      phase: 'Monofaze',
      battery_voltage_v: '40-65V',
      max_charge_discharge_a: 120,
      mppt_voltage_v: '70-540V',
      output: '50/60Hz, 230V',
      bms_communication: 'RS485',
    },
    description: '5 kW Monofaze Off-Grid LV. Batarya 40-65V, 120A şarj/deşarj. MPPT 70-540V. RS485 BMS.',
    descriptionEn: '5 kW single-phase Off-Grid LV. Battery 40-65V, 120A. MPPT 70-540V. RS485 BMS.',
    fullDescription: 'SRP 5 KW Monofaze Off-Grid İnverter Düşük Voltaj. Batarya çalışma voltajı: 40-65V. Maksimum şarj/deşarj akımı: 120A. MPPT voltaj aralığı: 70-540V. Çıkış: 50/60Hz, 230V. BMS haberleşme: RS485.',
    fullDescriptionEn: 'SRP 5 kW single-phase Off-Grid LV. Battery 40-65V, 120A max charge/discharge. MPPT 70-540V. Output 50/60Hz 230V. BMS: RS485.',
  },
  // ----- Monofaze Hibrit -----
  {
    slug: 'deye-5kw-monofaze-hibrit',
    name: 'DEYE 05 KW Monofaze Hibrit İnverter',
    nameEn: 'DEYE 5 kW Single-Phase Hybrid Inverter',
    brand: 'DEYE',
    mpn: 'SUN-5K-SG01LP1-EU',
    variantSku: 'SUN-5K-SG01LP1-EU',
    price: 1800,
    subCategory: 'monofaze_hibrit',
    specs: {
      power_kw: 5,
      phase: 'Monofaze',
      battery_voltage_v: '40-60V',
      max_charge_discharge_a: 120,
      mppt_voltage_v: '125-425V',
      mppt_trackers: 2,
      mppt_strings: '1+1 per tracker',
      pv_input_a: '13+13A',
      output: '50/60Hz, 220/230Vac',
      bms_communication: 'RS485, CAN',
    },
    description: '5 kW Monofaze Hibrit. Batarya 40-60V, 120A. MPPT 125-425V, 2 tracker. RS485, CAN.',
    descriptionEn: '5 kW single-phase hybrid. Battery 40-60V, 120A. MPPT 125-425V, 2 trackers. RS485, CAN.',
    fullDescription: 'DEYE 5 KW Monofaze Hibrit İnverter. Batarya çalışma voltajı: 40-60V. Maks şarj/deşarj: 120A. MPPT voltaj: 125-425V. 2 MPP Tracker (her biri 1+1 string). PV giriş akımı: 13+13A. Çıkış: 50/60Hz, 220/230Vac tek faz. BMS: RS485, CAN.',
    fullDescriptionEn: 'DEYE 5 kW single-phase hybrid. Battery 40-60V, 120A. MPPT 125-425V, 2 trackers. Output 50/60Hz 220/230Vac. BMS: RS485, CAN.',
  },
  {
    slug: 'deye-8kw-monofaze-hibrit',
    name: 'DEYE 08 KW Monofaze Hibrit İnverter',
    nameEn: 'DEYE 8 kW Single-Phase Hybrid Inverter',
    brand: 'DEYE',
    mpn: 'SUN-8K-SG01LP1-EU',
    variantSku: 'SUN-8K-SG01LP1-EU',
    price: 2850,
    subCategory: 'monofaze_hibrit',
    specs: {
      power_kw: 8,
      phase: 'Monofaze',
      battery_voltage_v: '40-60V',
      max_charge_discharge_a: 190,
      mppt_voltage_v: '150-425V',
      mppt_trackers: 2,
      mppt_strings: '2+2 per tracker',
      pv_input_a: '26+26A',
      output: '50/60Hz, 220/230Vac',
      bms_communication: 'RS485, RS232, CAN',
    },
    description: '8 kW Monofaze Hibrit. Batarya 40-60V, 190A. MPPT 150-425V, 2 tracker 2+2 string. RS485, RS232, CAN.',
    descriptionEn: '8 kW single-phase hybrid. Battery 40-60V, 190A. MPPT 150-425V. RS485, RS232, CAN.',
    fullDescription: 'DEYE 8 KW Monofaze Hibrit İnverter. Batarya: 40-60V, maks 190A şarj/deşarj. MPPT: 150-425V. 2 MPP Tracker (2+2 string). PV giriş: 26+26A. Çıkış: 50/60Hz, 220/230Vac. BMS: RS485, RS232, CAN.',
    fullDescriptionEn: 'DEYE 8 kW single-phase hybrid. Battery 40-60V, 190A. MPPT 150-425V, 2 trackers. BMS: RS485, RS232, CAN.',
  },
  {
    slug: 'srp-6kw-monofaze-hibrit-lv',
    name: 'SRP 06 KW Monofaze Hibrit İnverter - Düşük Voltaj (LV)',
    nameEn: 'SRP 6 kW Single-Phase Hybrid Inverter - Low Voltage (LV)',
    brand: 'SRP',
    mpn: 'HYBRİT-6KRS-H1-MF-LV',
    variantSku: 'HYBRID-6KRS-H1-MF-LV',
    price: 1977.08,
    subCategory: 'monofaze_hibrit',
    specs: {
      power_kw: 6,
      phase: 'Monofaze',
      battery_voltage_v: '40-60V',
      max_charge_discharge_a: 120,
      mppt_voltage_v: '70-540V',
      output: '50/60Hz, 230V',
      bms_communication: 'RS485',
    },
    description: '6 kW Monofaze Hibrit LV. Batarya 40-60V, 120A. MPPT 70-540V. RS485.',
    descriptionEn: '6 kW single-phase hybrid LV. Battery 40-60V, 120A. MPPT 70-540V. RS485.',
    fullDescription: 'SRP 6 KW Monofaze Hibrit İnverter Düşük Voltaj. Batarya: 40-60V, 120A. MPPT: 70-540V. Çıkış: 50/60Hz, 230V. Haberleşme: RS485.',
    fullDescriptionEn: 'SRP 6 kW single-phase hybrid LV. Battery 40-60V, 120A. MPPT 70-540V. RS485.',
  },
  // ----- Trifaze Hibrit -----
  {
    slug: 'deye-12kw-trifaze-hibrit',
    name: 'DEYE 12 KW Trifaze Hibrit İnverter',
    nameEn: 'DEYE 12 kW Three-Phase Hybrid Inverter',
    brand: 'DEYE',
    mpn: 'SUN-12K-SG04LP3',
    variantSku: 'SUN-12K-SG04LP3',
    price: 3900,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 12,
      phase: 'Trifaze',
      battery_voltage_v: '40-60V',
      max_charge_discharge_a: 240,
      mppt_voltage_v: '200-650V',
      mppt_trackers: 2,
      mppt_strings: '2+1',
      pv_input_a: '26+13A',
      output: '50/60Hz, 230/400Vac',
      bms_communication: 'RS485, CAN',
    },
    description: '12 kW Trifaze Hibrit. Batarya 40-60V, 240A. MPPT 200-650V. RS485, CAN.',
    descriptionEn: '12 kW three-phase hybrid. Battery 40-60V, 240A. MPPT 200-650V. RS485, CAN.',
    fullDescription: 'DEYE 12 KW Trifaze Hibrit İnverter. Batarya: 40-60V, maks 240A. MPPT: 200-650V. 2 MPP Tracker (2+1 string). PV giriş: 26+13A. Çıkış: 50/60Hz, 230/400Vac üç faz. BMS: RS485, CAN.',
    fullDescriptionEn: 'DEYE 12 kW three-phase hybrid. Battery 40-60V, 240A. MPPT 200-650V. Output 230/400Vac. BMS: RS485, CAN.',
  },
  {
    slug: 'deye-20kw-trifaze-hibrit-hv',
    name: 'DEYE 20 KW Trifaze Hibrit İnverter - Yüksek Voltaj (HV)',
    nameEn: 'DEYE 20 kW Three-Phase Hybrid Inverter - High Voltage (HV)',
    brand: 'DEYE',
    mpn: 'SUN-20K-SG01HP3-EU-HV',
    variantSku: 'SUN-20K-SG01HP3-EU-HV',
    price: 4133.32,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 20,
      phase: 'Trifaze',
      battery_voltage_v: '160-700V (HV)',
      max_charge_discharge_a: 37,
      mppt_voltage_v: '150-850V',
      mppt_trackers: 2,
      mppt_strings: '2+1',
      pv_input_a: '36+20A',
      output: '50/60Hz, 230/400Vac',
      bms_communication: 'RS485, RS232, CAN',
    },
    description: '20 kW Trifaze Hibrit HV. Batarya 160-700V, 37A. MPPT 150-850V. RS485, RS232, CAN.',
    descriptionEn: '20 kW three-phase hybrid HV. Battery 160-700V, 37A. MPPT 150-850V. RS485, RS232, CAN.',
    fullDescription: 'DEYE 20 KW Trifaze Hibrit İnverter Yüksek Voltaj. Batarya çalışma voltajı: 160-700V (HV). Maks şarj/deşarj: 37A. MPPT: 150-850V. 2 MPP Tracker (2+1 string). PV giriş: 36+20A. Çıkış: 50/60Hz, 230/400Vac. BMS: RS485, RS232, CAN.',
    fullDescriptionEn: 'DEYE 20 kW three-phase hybrid HV. Battery 160-700V, 37A. MPPT 150-850V. BMS: RS485, RS232, CAN.',
  },
  {
    slug: 'deye-20kw-trifaze-hibrit-lv',
    name: 'DEYE 20 KW Trifaze Hibrit İnverter - Düşük Voltaj (LV)',
    nameEn: 'DEYE 20 kW Three-Phase Hybrid Inverter - Low Voltage (LV)',
    brand: 'DEYE',
    mpn: 'SUN-20K-SG05LP3-EU-LV',
    variantSku: 'SUN-20K-SG05LP3-EU-LV',
    price: 5791.67,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kva: 20,
      power_kw: 20,
      phase: 'Trifaze',
      battery_voltage_v: '40-60V',
      max_charge_discharge_a: 37,
      mppt_voltage_v: '150-650V',
      mppt_trackers: 2,
      mppt_strings: '2+1',
      pv_input_a: '36+20A',
      output: '50/60Hz, 230/400Vac',
      bms_communication: 'RS485, RS232, CAN',
    },
    description: '20 kW Trifaze Hibrit LV. 20 kVA çıkış. Batarya 40-60V, 37A. MPPT 150-650V.',
    descriptionEn: '20 kW three-phase hybrid LV. Battery 40-60V, 37A. MPPT 150-650V.',
    fullDescription: 'DEYE 20 KW Trifaze Hibrit İnverter Düşük Voltaj. 20 kVA çıkış gücü (3 fazlı düşük voltaj). Batarya: 40-60V, 37A. MPPT: 150-650V. 2 MPP Tracker (2+1 string). PV: 36+20A. Çıkış: 50/60Hz, 230/400Vac. RS485, RS232, CAN.',
    fullDescriptionEn: 'DEYE 20 kW three-phase hybrid LV. 20 kVA output. Battery 40-60V, 37A. MPPT 150-650V. RS485, RS232, CAN.',
  },
  {
    slug: 'deye-25kw-trifaze-hibrit-hv',
    name: 'DEYE 25 KW Trifaze Hibrit İnverter - Yüksek Voltaj (HV)',
    nameEn: 'DEYE 25 kW Three-Phase Hybrid Inverter - High Voltage (HV)',
    brand: 'DEYE',
    mpn: 'SUN-25K-SG01HP3-EU',
    variantSku: 'SUN-25K-SG01HP3-EU',
    price: 4933.36,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 25,
      phase: 'Trifaze',
      voltage_type: 'HV',
      output: '50/60Hz, 230/400Vac',
    },
    description: '25 kW Trifaze Hibrit HV. Üç faz, yüksek voltaj batarya.',
    descriptionEn: '25 kW three-phase hybrid HV.',
    fullDescription: 'DEYE 25 KW Trifaze Hibrit İnverter Yüksek Voltaj (HV). 50/60Hz, 230/400Vac üç faz çıkış.',
    fullDescriptionEn: 'DEYE 25 kW three-phase hybrid inverter High Voltage (HV). 50/60Hz, 230/400Vac.',
  },
  {
    slug: 'deye-50kw-trifaze-hibrit-hv',
    name: 'DEYE 50 KW Trifaze Hibrit İnverter - Yüksek Voltaj (HV)',
    nameEn: 'DEYE 50 kW Three-Phase Hybrid Inverter - High Voltage (HV)',
    brand: 'DEYE',
    mpn: 'SUN-50K-SG01HP3-EU',
    variantSku: 'SUN-50K-SG01HP3-EU-HV',
    price: 9833.33,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 50,
      phase: 'Trifaze',
      battery_voltage_v: '160-800V',
      max_charge_discharge_a: '50+50A',
      mppt_voltage_v: '150-850V',
      mppt_trackers: 4,
      mppt_strings: '2 per tracker',
      pv_input_a: '36+36+36+36A',
      output: '50/60Hz, 230/400Vac',
    },
    description: '50 kW Trifaze Hibrit HV. Batarya 160-800V, 50+50A. 4 MPP Tracker.',
    descriptionEn: '50 kW three-phase hybrid HV. Battery 160-800V. 4 MPPT trackers.',
    fullDescription: 'DEYE 50 KW Trifaze Hibrit İnverter HV. Batarya: 160-800V, maks 50+50A şarj/deşarj. 4 adet MPP Tracker (her biri 2 string). MPPT voltaj: 150-850V. PV giriş: 36+36+36+36A. Çıkış: 50/60Hz, 230/400Vac üç faz.',
    fullDescriptionEn: 'DEYE 50 kW three-phase hybrid HV. Battery 160-800V, 50+50A. 4 MPPT trackers. Output 50/60Hz 230/400Vac.',
  },
  {
    slug: 'deye-80kw-trifaze-hibrit-hv',
    name: 'DEYE 80 KW Trifaze Hibrit İnverter - Yüksek Voltaj (HV)',
    nameEn: 'DEYE 80 kW Three-Phase Hybrid Inverter - High Voltage (HV)',
    brand: 'DEYE',
    mpn: 'SUN-80K-SG01HP3-EU',
    variantSku: 'SUN-80K-SG01HP3-EU-HV',
    price: 12876,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 80,
      phase: 'Trifaze',
      voltage_type: 'HV',
      output: '50/60Hz, 230/400Vac',
    },
    description: '80 kW Trifaze Hibrit HV. Üç faz, yüksek voltaj.',
    descriptionEn: '80 kW three-phase hybrid HV.',
    fullDescription: 'DEYE 80 KW Trifaze Hibrit İnverter Yüksek Voltaj (HV). 50/60Hz, 230/400Vac üç faz.',
    fullDescriptionEn: 'DEYE 80 kW three-phase hybrid inverter High Voltage (HV).',
  },
  {
    slug: 'srp-15kw-trifaze-hibrit-lv',
    name: 'SRP 15 KW Trifaze Hibrit İnverter - Düşük Voltaj (LV)',
    nameEn: 'SRP 15 kW Three-Phase Hybrid Inverter - Low Voltage (LV)',
    brand: 'SRP',
    mpn: 'HYBRİD-15KCT-H1-TF-LV',
    variantSku: 'HYBRID-15KCT-H1-TF-LV',
    price: 4986.58,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 15,
      phase: 'Trifaze',
      battery_voltage_v: '40-65V',
      max_charge_discharge_a: 300,
      mppt_voltage_v: '350-850V',
      output: '50/60Hz, 230V',
      bms_communication: 'RS485',
    },
    description: '15 kW Trifaze Hibrit LV. Batarya 40-65V, 300A. MPPT 350-850V. RS485.',
    descriptionEn: '15 kW three-phase hybrid LV. Battery 40-65V, 300A. MPPT 350-850V. RS485.',
    fullDescription: 'SRP 15 KW Trifaze Hibrit İnverter Düşük Voltaj. Batarya: 40-65V, maks 300A. MPPT: 350-850V. Çıkış: 50/60Hz, 230V. Haberleşme: RS485.',
    fullDescriptionEn: 'SRP 15 kW three-phase hybrid LV. Battery 40-65V, 300A. MPPT 350-850V. RS485.',
  },
  {
    slug: 'srp-30kw-trifaze-hibrit-hv',
    name: 'SRP 30 KW Trifaze Hibrit İnverter - Yüksek Voltaj (HV)',
    nameEn: 'SRP 30 kW Three-Phase Hybrid Inverter - High Voltage (HV)',
    brand: 'SRP',
    mpn: 'HYBRİD-30KCT-H1-TF-HV',
    variantSku: 'HYBRID-30KCT-H1-TF-HV',
    price: 6878.08,
    subCategory: 'trifaze_hibrit',
    specs: {
      power_kw: 30,
      phase: 'Trifaze',
      battery_voltage_v: '40-65V',
      max_charge_discharge_a: 300,
      mppt_voltage_v: '350-900V',
      output: '50/60Hz, 230V',
      bms_communication: 'RS485',
    },
    description: '30 kW Trifaze Hibrit HV. Batarya 40-65V, 300A. MPPT 350-900V. RS485.',
    descriptionEn: '30 kW three-phase hybrid HV. Battery 40-65V, 300A. MPPT 350-900V. RS485.',
    fullDescription: 'SRP 30 KW Trifaze Hibrit İnverter Yüksek Voltaj. Batarya: 40-65V, maks 300A. MPPT: 350-900V. Çıkış: 50/60Hz, 230V. Haberleşme: RS485.',
    fullDescriptionEn: 'SRP 30 kW three-phase hybrid HV. Battery 40-65V, 300A. MPPT 350-900V. RS485.',
  },
]

async function main() {
  console.log('🌱 İnverter Sistemleri seed: kategori ve ürünler...')

  const inverterCategory = await prisma.category.upsert({
    where: { slug: 'inverter-sistemleri' },
    create: {
      slug: 'inverter-sistemleri',
      name: 'İnverter Sistemleri',
      nameEn: 'Inverter Systems',
      description: 'Şebekeden bağımsız (Off-Grid), monofaze ve trifaze hibrit inverterler. ORBİT, DEYE, SRP.',
      descriptionEn: 'Off-grid, single-phase and three-phase hybrid inverters. ORBİT, DEYE, SRP.',
      order: 4,
      active: true,
    },
    update: {
      name: 'İnverter Sistemleri',
      nameEn: 'Inverter Systems',
    },
  })

  for (const p of inverterProducts) {
    const prod = await prisma.product.upsert({
      where: { slug: p.slug },
      create: {
        slug: p.slug,
        name: p.name,
        nameEn: p.nameEn,
        brand: p.brand,
        mpn: p.mpn,
        sku: p.variantSku,
        lifecycle: Lifecycle.ACTIVE,
        certifications: { ce: true },
        specs: p.specs,
        description: p.description,
        descriptionEn: p.descriptionEn,
        fullDescription: p.fullDescription,
        fullDescriptionEn: p.fullDescriptionEn,
        images: [{ url: '/images/products/inverter-placeholder.jpg', alt: p.name, order: 1 }],
        categoryId: inverterCategory.id,
        leadTimeDays: 14,
        moq: 1,
        orderStep: 1,
        active: true,
      },
      update: {
        name: p.name,
        nameEn: p.nameEn,
        description: p.description,
        fullDescription: p.fullDescription,
        specs: p.specs,
        categoryId: inverterCategory.id,
      },
    })
    await prisma.variant.upsert({
      where: { sku: p.variantSku },
      create: {
        productId: prod.id,
        sku: p.variantSku,
        matrix: { subCategory: p.subCategory, power: p.specs.power_kw ?? p.specs.power_kva, brand: p.brand },
        price: p.price,
        currency: 'USD',
        vatRate: 20,
        weightG: null,
        isActive: true,
        stock: { create: { onHand: 3, reserved: 0, incoming: 2 } },
      },
      update: { price: p.price, currency: 'USD' },
    })
  }

  console.log('✅ İnverter Sistemleri seed tamamlandı: 1 kategori, ' + inverterProducts.length + ' ürün.')
}

main()
  .catch((e) => {
    console.error('❌ İnverter seed hatası:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
