/**
 * ORBİT Lityum (LiFePO4) Aküler ve İnverter Sistemleri (DEYE, SRP, ORBİT).
 * Kategoriler: Lityum (LiFePO4) Aküler, Off-Grid İnverterler, İnverter Sistemleri.
 */

import type { MockProduct } from './products-mock'

/** Placeholder path (products-mock ile döngüyü önlemek için burada tanımlı). */
const PLACEHOLDER = '/images/products/placeholder.png'

function spec(o: Record<string, string>): Record<string, string> {
  return o
}

const LIFEPO4_CATEGORY = 'Lityum (LiFePO4) Aküler'
const OFFGRID_CATEGORY = 'Off-Grid İnverterler'
const INVERTER_SYSTEMS_CATEGORY = 'İnverter Sistemleri'

export const mockProductsOrbitInverters: MockProduct[] = [
  // ----- 12V Lityum Aküler -----
  {
    id: 'orbit-12v-100ah-abs',
    sku: 'GU12100',
    name: 'ORBİT 12 V 100 Ah LiFePO4 Akü - ABS Kasa',
    description: '6000 Cycle (%80 D.O.D), prizmatik hücre, ABS kasa. Ekran ve Bluetooth.',
    price: 526,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-12v-100ah-abs-1.jpg',
    fullDescription: 'ORBİT 12V 100Ah LiFePO4 akü, prizmatik hücre yapısına ve ABS kasaya sahiptir. Bluetooth ve ekran özellikleri mevcuttur. Şarj durumu sıcaklık aralığı 0ºC ile 60ºC, deşarj durumu ise -20ºC ile 60ºC arasındadır (Nominal çalışma sıcaklığı: 25ºC). 6000 Cycle %80 D.O.D ömür.',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8373 / GU12100 / OE-12V100Ah-P-ABS',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik (Prismatic)',
      'Kasa Tipi': 'ABS',
      'Şarj Sıcaklığı': '0ºC - 60ºC',
      'Deşarj Sıcaklığı': '-20ºC - 60ºC',
      'Nominal Çalışma Sıcaklığı': '25ºC',
      'Ekran': 'Var',
      'Bluetooth': 'Var',
      'Boyutlar (G x D x Y)': '332mm x 171mm x 220mm',
      'Ağırlık': '13 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Prizmatik hücre', 'ABS kasa', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-12v-200ah-abs',
    sku: 'GU12200',
    name: 'ORBİT 12 V 200 Ah LiFePO4 Akü - ABS Kasa',
    description: '6000 Cycle (%80 D.O.D), prizmatik hücre, ABS kasa. Ekran ve Bluetooth.',
    price: 835.33,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-12v-200ah-abs-1.jpg',
    fullDescription: 'ORBİT 12V 200Ah LiFePO4 akü, 6000 Cycle (%80 D.O.D) ömre, prizmatik hücrelere ve ABS kasaya sahiptir. Cihazda ekran ve Bluetooth desteği bulunmaktadır.',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8195 / GU12200 / OE-12V200Ah-P-ABS',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik (Prismatic)',
      'Kasa Tipi': 'ABS',
      'Boyutlar (G x D x Y)': '498mm x 244mm x 220mm',
      'Ağırlık': '23 kg',
      'Ekran / Bluetooth': 'Var',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Prizmatik hücre', 'ABS kasa', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-12v-420ah-abs',
    sku: 'GU12420',
    name: 'ORBİT 12 V 420 Ah LiFePO4 Akü - ABS Kasa',
    description: '6000 Cycle (%80 D.O.D), ABS kasa, prizmatik hücre. Ekran ve Bluetooth.',
    price: 1652.74,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-12v-420ah-abs-1.jpg',
    fullDescription: 'ORBİT 12V 420Ah LiFePO4 akü, ABS kasalı, prizmatik hücreli, ekranlı ve Bluetooth destekli. 6000 Cycle (%80 D.O.D) dayanıklılığa sahiptir.',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8431 / GU12420 / OE-12V420Ah-P-ABS',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik (Prismatic)',
      'Kasa Tipi': 'ABS',
      'Boyutlar (G x D x Y)': '635mm x 244mm x 220mm',
      'Ağırlık': '43 kg',
      'Ekran / Bluetooth': 'Var',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Prizmatik hücre', 'ABS kasa', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-12v-100ah-marin',
    sku: 'VP12100',
    name: 'ORBİT 12 V 100 Ah LiFePO4 Akü - Marin Tip (Victron Uyumlu)',
    description: 'Marin kullanım, Victron uyumlu. 6000 Cycle, ekran ve Bluetooth.',
    price: 698,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-12v-100ah-marin-1.jpg',
    fullDescription: 'ORBİT 12V 100Ah LiFePO4 akü, Marin tip (VP Serisi). ABS kasalı ve prizmatik hücreli, Victron sistemleri ile uyumludur. 6000 Cycle (%80 D.O.D), ekran ve Bluetooth.',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8330 / VP12100 / OE-12V100Ah-P-ABS-MARINE',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik (Prismatic)',
      'Kasa Tipi': 'ABS',
      'Victron Uyumluluk': 'Var',
      'Ekran / Bluetooth': 'Var',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Victron uyumlu', 'Marin tip', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-12v-200ah-marin',
    sku: 'VP12200',
    name: 'ORBİT 12 V 200 Ah LiFePO4 Akü - Marin Tip (Victron Uyumlu)',
    description: 'Victron uyumlu marin tip. 6000 Cycle, Bluetooth ve ekran.',
    price: 975,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-12v-200ah-marin-1.jpg',
    fullDescription: 'ORBİT 12V 200Ah LiFePO4 akü, Marin tip (VP Serisi). Victron uyumluluğuna sahip, ABS kasalı. 6000 Cycle (%80 D.O.D), Bluetooth ve ekran mevcuttur.',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8332 / VP12200 / OE-12V200Ah-P-ABS-MARINE',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '508,3mm x 202,4mm x 189,3mm',
      'Ağırlık': '23 kg',
      'Victron Uyumluluk': 'Var',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Victron uyumlu', 'Marin tip', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-12v-420ah-marin',
    sku: 'VP12420',
    name: 'ORBİT 12 V 420 Ah LiFePO4 Akü - Marin Tip (Victron Uyumlu)',
    description: '6000 Cycle, marin tip, Victron uyumlu. Bluetooth ve ekran.',
    price: 1750,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-12v-420ah-marin-1.jpg',
    fullDescription: 'ORBİT 12V 420Ah LiFePO4 akü, Marin tip (VP Serisi). 6000 Cycle (%80 D.O.D), Victron sistemleriyle tam uyumludur. Bluetooth ve ekrana sahiptir.',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8432 / VP12420 / OE-12V420Ah-P-ABS-MARINE',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '242mm x 630mm x 226mm',
      'Ağırlık': '43 kg',
      'Victron Uyumluluk': 'Var',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Victron uyumlu', 'Marin tip', 'Ekran ve Bluetooth'],
  },
  // ----- 24V Lityum Aküler -----
  {
    id: 'orbit-24v-100ah-abs',
    sku: 'GU24100',
    name: 'ORBİT 24 V 100 Ah LiFePO4 Akü - ABS Kasa',
    description: '6000 Cycle (%80 D.O.D), prizmatik hücre, ekran ve Bluetooth.',
    price: 784.17,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-24v-100ah-abs-1.jpg',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8079 / GU24100 / OE-24V100Ah-P-ABS',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '498mm x 244mm x 220mm',
      'Ağırlık': '23 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Prizmatik hücre', 'ABS kasa', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-24v-150ah-abs',
    sku: 'GU24150',
    name: 'ORBİT 24 V 150 Ah LiFePO4 Akü - ABS Kasa',
    description: '6000 Cycle (%80 D.O.D), ABS kasa, ekran ve Bluetooth.',
    price: 1248,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: PLACEHOLDER,
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8220 / GU24150 / OE-24V150Ah-P-ABS',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '508,3mm x 202,4mm x 189,3mm',
    }),
    features: ['6000 Cycle %80 D.O.D', 'ABS kasa', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-24v-210ah-abs',
    sku: 'GU24210',
    name: 'ORBİT 24 V 210 Ah LiFePO4 Akü - ABS Kasa',
    description: '8000 Cycle (%80 D.O.D). Elektrikli araç, karavan, tekne için uygun.',
    price: 1652.74,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-24v-210ah-abs-1.jpg',
    specifications: spec({
      'POZ / Model': '8398 / GU24210',
      'Çevrim Ömrü (Cycle)': '8000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '635mm x 244mm x 220mm',
      'Ağırlık': '43 kg',
      'Kullanım Alanları': 'Elektrikli araç, Karavan, Tekne',
    }),
    features: ['8000 Cycle %80 D.O.D', 'Prizmatik hücre', 'Ekran ve Bluetooth'],
  },
  {
    id: 'orbit-24v-100ah-marin',
    sku: 'VP24100',
    name: 'ORBİT 24 V 100 Ah LiFePO4 Akü - Marin Tip (Victron Uyumlu)',
    description: 'Victron uyumlu marin akü. 6000 Cycle, ekran ve Bluetooth.',
    price: 960,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-24v-100ah-marin-1.jpg',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8333 / VP24100 / OE-24V100Ah-P-ABS-MARINE',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '508,3mm x 202,4mm x 189,3mm',
      'Ağırlık': '23 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Victron uyumlu', 'Marin tip'],
  },
  {
    id: 'orbit-24v-210ah-marin',
    sku: 'VP24210',
    name: 'ORBİT 24 V 210 Ah LiFePO4 Akü - Marin Tip (Victron Uyumlu)',
    description: 'Karavan ve tekne için. 8000 Cycle, ekran ve Bluetooth.',
    price: 1735,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-24v-210ah-marin-1.jpg',
    specifications: spec({
      'POZ / Model': '8399 / VP24210',
      'Çevrim Ömrü (Cycle)': '8000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '242mm x 630mm x 226mm',
      'Ağırlık': '43 kg',
      'Kullanım Alanları': 'Karavan, Tekne',
    }),
    features: ['8000 Cycle %80 D.O.D', 'Victron uyumlu', 'Marin tip'],
  },
  // ----- 48V Lityum Aküler -----
  {
    id: 'orbit-48v-100ah-wall',
    sku: 'GU48100WT',
    name: 'ORBİT 48 V 100 Ah LiFePO4 Akü - Ekranlı Duvar Tipi',
    description: 'Duvar tipi montaj, metal kasa, ekranlı. 6000 Cycle (%80 D.O.D).',
    price: 1454,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-48v-100ah-wall-1.jpg',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8287 / GU48100WT / OE-48V100Ah-P-W-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Kasa Tipi': 'Metal Kasa (Duvar Tipi)',
      'Boyutlar (G x Y x D)': '430mm x 436mm x 158mm',
      'Ağırlık': '43 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Duvar tipi', 'Ekranlı', 'Metal kasa'],
  },
  {
    id: 'orbit-48v-100ah-ys',
    sku: 'GU48100YS',
    name: 'ORBİT 48 V 100 Ah LiFePO4 Akü - Ekranlı Metal Kasa',
    description: 'Ekranlı metal kasa. 6000 Cycle (%80 D.O.D).',
    price: 1416.46,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-48v-100ah-ys-1.png',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8285 / GU48100YS / OE-48V100Ah-P-YS-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '430mm x 436mm x 158mm',
      'Ağırlık': '43 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Ekranlı', 'Metal kasa'],
  },
  {
    id: 'orbit-48v-100ah-ns',
    sku: 'GU48100NS',
    name: 'ORBİT 48 V 100 Ah LiFePO4 Akü - Ekransız Metal Kasa',
    description: 'Ekransız standart metal kasa. 6000 Cycle (%80 D.O.D) prizmatik hücre.',
    price: 1390,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-48v-100ah-ns-1.jpg',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8208 / GU48100NS / OE-48V100Ah-P-NS-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Kasa Tipi': 'Metal Kasa (Ekransız)',
      'Boyutlar (G x D x Y)': '430mm x 436mm x 158mm',
      'Ağırlık': '43 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'Prizmatik hücre', 'Metal kasa'],
  },
  // ----- 51.2V Lityum Aküler -----
  {
    id: 'orbit-51v2-50ah-hv',
    sku: 'GU51050HV',
    name: 'ORBİT 51.2 V 50 Ah LiFePO4 Akü - High Voltage (HV) Metal Kasa',
    description: 'Yüksek voltaj, raf tipi montaj. Slave BMS, tek başına satılamaz. 6000 Cycle.',
    price: 1179.18,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-51v2-50ah-hv-1.jpg',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8374 / GU51050HV / OE-51.2V50Ah-P-HV-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik - Slave BMS',
      'Montaj': 'Raf Tipi (Rack Mounted)',
      'Uyarı': 'Tek başına satılamaz',
      'Boyutlar (G x D x Y)': '230mm x 235mm x 145mm',
      'Ağırlık': '30 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'HV', 'Raf tipi', 'Slave BMS'],
  },
  {
    id: 'orbit-51v2-100ah-hv',
    sku: 'GU51100HV',
    name: 'ORBİT 51.2 V 100 Ah LiFePO4 Akü - High Voltage (HV) Metal Kasa',
    description: 'HV, raf tipi montaj. Tek başına satılamaz. 6000 Cycle (%80 D.O.D).',
    price: 1448.41,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-51v2-100ah-hv-1.png',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8031 / GU51100HV / OE-51.2V100Ah-P-HV-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '437mm x 435mm x 159mm',
      'Ağırlık': '45 kg',
      'Uyarı': 'Tek başına satılamaz',
    }),
    features: ['6000 Cycle %80 D.O.D', 'HV', 'Raf tipi'],
  },
  {
    id: 'orbit-51v2-100ah-lv',
    sku: 'GU51100LV',
    name: 'ORBİT 51.2 V 100 Ah LiFePO4 Akü - Low Voltage (LV) Ekranlı Metal Kasa',
    description: 'Düşük voltaj (LV), ekranlı metal kasa. 6000 Cycle (%80 D.O.D).',
    price: 1459.06,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-51v2-100ah-lv-1.png',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8255 / GU51100LV / OE-51.2V100Ah-P-YS-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Boyutlar (G x D x Y)': '430mm x 436mm x 158mm',
      'Ağırlık': '45 kg',
    }),
    features: ['6000 Cycle %80 D.O.D', 'LV', 'Ekranlı', 'Metal kasa'],
  },
  {
    id: 'orbit-51v2-280ah-lv-trinity2',
    sku: 'GU51280LV-TRINITY2',
    name: 'ORBİT 51.2 V 280 Ah LiFePO4 Akü - Low Voltage (LV) Metal Kasa (TRİNİTY2)',
    description: 'LV serisi prizmatik hücreli metal kasa. 6000 Cycle (%80 D.O.D).',
    price: 3619,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-51v2-280ah-lv-trinity2-1.png',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8465 / GU51280LV-TRİNİTY2 / OE-51.2V280Ah-P-LV-YS-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik (Prismatic)',
      'Kasa Tipi': 'Metal Kasa',
    }),
    features: ['6000 Cycle %80 D.O.D', 'LV', 'TRİNİTY2', 'Prizmatik hücre'],
  },
  {
    id: 'orbit-51v2-314ah-lv-trinity3',
    sku: 'GU51314LVP10-TRINITY3',
    name: 'ORBİT 51.2 V 314 Ah LiFePO4 Akü - Low Voltage (LV) Metal Kasa (TRİNİTY3)',
    description: 'Prizmatik hücreli, düşük voltajlı. 6000 Cycle (%80 D.O.D) metal kasalı seri.',
    price: 3649,
    category: LIFEPO4_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-51v2-314ah-lv-trinity3-1.png',
    specifications: spec({
      'POZ / Model / Ürün Kodu': '8503 / GU51314LVP10-TRİNİTY3 / OE-51.2V314Ah-P-LV-YS-METAL',
      'Çevrim Ömrü (Cycle)': '6000 Cycle (%80 D.O.D)',
      'Hücre Tipi': 'Prizmatik (Prismatic)',
      'Kasa Tipi': 'Metal Kasa',
    }),
    features: ['6000 Cycle %80 D.O.D', 'LV', 'TRİNİTY3', 'Prizmatik hücre'],
  },
  // ----- Off-Grid İnverterler -----
  {
    id: 'orbit-6-2kw-offgrid-parallel',
    sku: 'M6200-48PL',
    name: 'ORBİT 6.2 KW Tam Sinüs Off-Grid İnverter (12 Cihaz Paralellenebilir)',
    description: 'LiFePO4 uyumlu, 12 cihaza kadar paralel. 500 VDC PV, 120A MPPT. Tam sinüs, aküsüz çalışma.',
    price: 566.66,
    category: OFFGRID_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-6-2kw-offgrid-parallel-1.png',
    fullDescription: 'LiFePO4 akülerle tam uyumlu çalışır ve 12 cihaza kadar paralel bağlanabilir (tek veya 3 fazda). Tam sinüs dalga çıkışı ve 1.0 güç faktörü. Maksimum 500 VDC PV girişi, 120A dahili MPPT şarj kontrolörü. Aküsüz çalışabilme, WiFi dongle, çıkarılabilir toz filtresi, EQ fonksiyonu.',
    specifications: spec({
      'POZ / Model': '8483 / M6200-48PL',
      'Dalga Çıkışı': 'Tam Sinüs (Pure Sine Wave)',
      'Güç Faktörü': '1.0',
      'PV Giriş': 'Maks. 500 VDC',
      'MPPT': '120A dahili',
      'Paralel': '12 cihaza kadar (tek/3 faz)',
      'WiFi': 'Dongle desteği',
    }),
    features: ['LiFePO4 uyumlu', '12 cihaz paralel', '500 VDC PV', '120A MPPT', 'Aküsüz çalışma', 'EQ fonksiyonu'],
  },
  {
    id: 'orbit-6-2kw-offgrid-non-parallel',
    sku: 'M6200-48',
    name: 'ORBİT 6.2 KW Tam Sinüs Off-Grid İnverter (Paralel Olmayan)',
    description: 'Tam sinüs, LiFePO4 uyumlu. 500 VDC PV, 120A MPPT. Paralel özelliği yok.',
    price: 506.72,
    category: OFFGRID_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'ORBİT',
    image: '/images/products/orbit-6-2kw-offgrid-non-parallel-1.png',
    specifications: spec({
      'POZ / Model': '8484 / M6200-48',
      'Dalga Çıkışı': 'Tam Sinüs',
      'PV Giriş': 'Maks. 500 VDC',
      'MPPT': '120A',
      'Paralel': 'Desteklemez',
    }),
    features: ['LiFePO4 uyumlu', '500 VDC PV', '120A MPPT', 'Aküsüz çalışma'],
  },
  {
    id: 'srp-5kw-offgrid-mf-lv',
    sku: 'OFFGRID-5KRS-F1-MF-LV',
    name: 'SRP 05 KW Monofaze Off-Grid İnverter - LV',
    description: 'Batarya 40-65V, 120A şarj/deşarj. MPPT 70-540V. 50/60Hz, 230V. RS485.',
    price: 584.65,
    category: OFFGRID_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'SRP',
    image: PLACEHOLDER,
    specifications: spec({
      'POZ / Model': '8485 / OFFGRİD-5KRS-F1-MF-LV',
      'Batarya Voltaj Aralığı': '40-65V',
      'Maks. Şarj/Deşarj Akımı': '120A',
      'MPPT Voltaj Aralığı': '70-540V',
      'Çıkış': '50/60Hz, 230V',
      'BMS Haberleşme': 'RS485',
    }),
    features: ['Monofaze', 'LV', '120A', 'MPPT 70-540V', 'RS485'],
  },
  // ----- Monofaze Hibrit İnverterler (İnverter Sistemleri) -----
  {
    id: 'deye-5kw-monofaze-hybrid',
    sku: 'SUN-5K-SG01LP1-EU',
    name: 'DEYE 05 KW Monofaze Hibrit İnverter',
    description: 'MPPT 125-425V (2 MPPT). Batarya 40-60V, 120A. 220/230Vac. RS485, CAN.',
    price: 1800,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-5kw-monofaze-hybrid-1.jpg',
    specifications: spec({
      'POZ / Model': '7938 / SUN-5K-SG01LP1-EU',
      'Batarya Voltaj Aralığı': '40-60V',
      'Maks. Şarj/Deşarj Akımı': '120A',
      'MPPT Voltaj Aralığı': '125-425V',
      'MPP Tracker': '2 (1+1 String)',
      'Çıkış': '50/60Hz, 220/230Vac (Tek Faz)',
      'BMS': 'RS485, CAN',
    }),
    features: ['Monofaze Hibrit', '2 MPPT', '120A', 'RS485/CAN'],
  },
  {
    id: 'deye-8kw-monofaze-hybrid',
    sku: 'SUN-8K-SG01LP1-EU',
    name: 'DEYE 08 KW Monofaze Hibrit İnverter',
    description: '190A şarj/deşarj. Batarya 40-60V. MPPT 150-425V. RS485, RS232, CAN.',
    price: 2850,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-8kw-monofaze-hybrid-1.jpg',
    specifications: spec({
      'POZ / Model': '7939 / SUN-8K-SG01LP1-EU',
      'Batarya Voltaj Aralığı': '40-60V',
      'Maks. Şarj/Deşarj Akımı': '190A',
      'MPPT Voltaj Aralığı': '150-425V',
      'MPP Tracker': '2 (2+2 String)',
      'PV Giriş Akımı': '26+26A',
      'BMS': 'RS485, RS232, CAN',
    }),
    features: ['Monofaze Hibrit', '190A', '2 MPPT', 'RS485/RS232/CAN'],
  },
  {
    id: 'srp-6kw-monofaze-hybrid-lv',
    sku: 'HYBRIT-6KRS-H1-MF-LV',
    name: 'SRP 06 KW Monofaze Hibrit İnverter - LV',
    description: 'MPPT 70-540V. Batarya 40-60V, 120A. 50/60Hz, 230V. RS485.',
    price: 1977.08,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'SRP',
    image: '/images/products/srp-6kw-monofaze-hybrid-lv-1.png',
    specifications: spec({
      'POZ / Model': '8486 / HYBRİT-6KRS-H1-MF-LV',
      'Batarya Voltaj Aralığı': '40-60V',
      'Maks. Şarj/Deşarj Akımı': '120A',
      'MPPT Voltaj Aralığı': '70-540V',
      'Çıkış': '50/60Hz, 230V',
      'BMS': 'RS485',
    }),
    features: ['Monofaze Hibrit', 'LV', '120A', 'MPPT 70-540V'],
  },
  // ----- Trifaze Hibrit İnverterler -----
  {
    id: 'deye-12kw-trifaze-hybrid',
    sku: 'SUN-12K-SG04LP3',
    name: 'DEYE 12 KW Trifaze Hibrit İnverter',
    description: 'Batarya 40-60V, 240A. MPPT 200-650V. 230/400Vac. RS485, CAN.',
    price: 3900,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-12kw-trifaze-hybrid-1.jpg',
    specifications: spec({
      'POZ / Model': '7959 / SUN-12K-SG04LP3',
      'Batarya Voltaj Aralığı': '40-60V',
      'Maks. Şarj/Deşarj Akımı': '240A',
      'MPPT Voltaj Aralığı': '200-650V',
      'MPP Tracker': '2 (2+1 String)',
      'Çıkış': '50/60Hz, 230/400Vac (Üç Faz)',
      'BMS': 'RS485, CAN',
    }),
    features: ['Trifaze Hibrit', '240A', 'MPPT 200-650V'],
  },
  {
    id: 'deye-20kw-trifaze-hv',
    sku: 'SUN-20K-SG01HP3-EU-HV',
    name: 'DEYE 20 KW Trifaze Hibrit İnverter - High Voltage (HV)',
    description: 'Batarya 160-700V (HV). 37A şarj/deşarj. MPPT 150-850V. RS485, RS232, CAN.',
    price: 4133.32,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-20kw-trifaze-hv-1.jpg',
    specifications: spec({
      'POZ / Model': '8181 / SUN-20K-SG01HP3-EU-HV',
      'Batarya Voltaj Aralığı': '160-700V (HV)',
      'Maks. Şarj/Deşarj Akımı': '37A',
      'MPPT Voltaj Aralığı': '150-850V',
      'Çıkış': '50/60Hz, 230/400Vac (Üç Faz)',
      'BMS': 'RS485, RS232, CAN',
    }),
    features: ['Trifaze Hibrit', 'HV', '37A', 'MPPT 150-850V'],
  },
  {
    id: 'deye-20kw-trifaze-lv',
    sku: 'SUN-20K-SG05LP3-EU-LV',
    name: 'DEYE 20 KW Trifaze Hibrit İnverter - Low Voltage (LV)',
    description: '20 kVA, 3 fazlı LV. Batarya 40-60V, 37A. MPPT 150-650V.',
    price: 5791.67,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-20kw-trifaze-lv-1.jpg',
    specifications: spec({
      'POZ / Model': '8454 / SUN-20K-SG05LP3-EU-LV',
      'Çıkış Gücü': '20 kVA (3 Fazlı LV)',
      'Batarya Voltaj Aralığı': '40-60V',
      'Maks. Şarj/Deşarj Akımı': '37A',
      'MPPT Voltaj Aralığı': '150-650V',
      'Çıkış': '50/60Hz, 230/400Vac',
      'BMS': 'RS485, RS232, CAN',
    }),
    features: ['Trifaze Hibrit', 'LV', '20 kVA', '37A'],
  },
  {
    id: 'deye-25kw-trifaze-hv',
    sku: 'SUN-25K-SG01HP3-EU',
    name: 'DEYE 25 KW Trifaze Hibrit İnverter - High Voltage (HV)',
    description: 'Yüksek voltajlı trifaze hibrit inverter.',
    price: 4933.36,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-25kw-trifaze-hv-1.jpg',
    specifications: spec({
      'POZ / Model': '8180 / SUN-25K-SG01HP3-EU',
      'Tip': 'Trifaze Hibrit HV',
    }),
    features: ['Trifaze Hibrit', 'HV', '25 KW'],
  },
  {
    id: 'deye-50kw-trifaze-hv',
    sku: 'SUN-50K-SG01HP3-EU-HV',
    name: 'DEYE 50 KW Trifaze Hibrit İnverter - High Voltage (HV)',
    description: 'Endüstriyel. Batarya 160-800V. 4 MPP Tracker. 50+50A şarj/deşarj. MPPT 150-850V.',
    price: 9833.33,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-50kw-trifaze-hv-1.jpg',
    specifications: spec({
      'POZ / Model': '8155 / SUN-50K-SG01HP3-EU HV',
      'Batarya Voltaj Aralığı': '160-800V',
      'Maks. Şarj/Deşarj Akımı': '50+50A',
      'MPP Tracker': '4 adet',
      'MPPT Voltaj Aralığı': '150-850V',
      'Çıkış': '50/60Hz, 230/400Vac (Üç Faz)',
    }),
    features: ['Trifaze Hibrit', 'HV', '50 KW', '4 MPPT', 'Endüstriyel'],
  },
  {
    id: 'deye-80kw-trifaze-hv',
    sku: 'SUN-80K-SG01HP3-EU-HV',
    name: 'DEYE 80 KW Trifaze Hibrit İnverter - High Voltage (HV)',
    description: 'Yüksek kapasiteli HV trifaze hibrit inverter.',
    price: 12876,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'DEYE',
    image: '/images/products/deye-80kw-trifaze-hv-1.png',
    specifications: spec({
      'POZ / Model': '8481 / SUN-80K-SG01HP3-EU HV',
      'Tip': 'Trifaze Hibrit HV, 80 KW',
    }),
    features: ['Trifaze Hibrit', 'HV', '80 KW'],
  },
  {
    id: 'srp-15kw-trifaze-lv',
    sku: 'HYBRID-15KCT-H1-TF-LV',
    name: 'SRP 15 KW Trifaze Hibrit İnverter - LV',
    description: 'Batarya 40-65V, 300A. MPPT 350-850V. 50/60Hz, 230V. RS485.',
    price: 4986.58,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'SRP',
    image: '/images/products/srp-15kw-trifaze-lv-1.png',
    specifications: spec({
      'POZ / Model': '8487 / HYBRİD-15KCT-H1-TF-LV',
      'Batarya Voltaj Aralığı': '40-65V',
      'Maks. Şarj/Deşarj Akımı': '300A',
      'MPPT Voltaj Aralığı': '350-850V',
      'Çıkış': '50/60Hz, 230V',
      'BMS': 'RS485',
    }),
    features: ['Trifaze Hibrit', 'LV', '300A', 'MPPT 350-850V'],
  },
  {
    id: 'srp-30kw-trifaze-hv',
    sku: 'HYBRID-30KCT-H1-TF-HV',
    name: 'SRP 30 KW Trifaze Hibrit İnverter - HV',
    description: 'Yüksek voltaj. MPPT 350-900V. 300A şarj/deşarj. RS485.',
    price: 6878.08,
    category: INVERTER_SYSTEMS_CATEGORY,
    stock: 0,
    featured: false,
    isVariantProduct: false,
    brand: 'SRP',
    image: '/images/products/srp-30kw-trifaze-hv-1.png',
    specifications: spec({
      'POZ / Model': '8488 / HYBRİD-30KCT-H1-TF-HV',
      'Batarya Voltaj Aralığı': '40-65V',
      'Maks. Şarj/Deşarj Akımı': '300A',
      'MPPT Voltaj Aralığı': '350-900V',
      'Çıkış': '50/60Hz, 230V',
      'BMS': 'RS485',
    }),
    features: ['Trifaze Hibrit', 'HV', '300A', 'MPPT 350-900V'],
  },
]
