/**
 * Elektromarketim'den çekilen ürünler (apply-electromarketim-by-url-to-mock.ts ile üretilir).
 * products-mock.ts bu diziyi mockProducts ile birleştirir.
 */

import type { MockProduct } from './products-mock'

export const mockProductsElectromarketim: MockProduct[] = [
  {
    id: 'hims-emef-22t2-sb-10-cnt',
    sku: 'EMEF-22T2-SB-10-CNT',
    name: 'Hims EMEF-22T2-SB-10 22kW Tip 2 Soketli 10m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 10m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 10m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 10m Araç Şarj Kablosu Hims markasının ürettiği 10',
    fullDescription: 'Hims 22kW Destekli 10m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 10m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 10m Araç Şarj Kablosu Hims markasının ürettiği 10m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 10 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 10 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Rengi : Siyah Aksesuar : Çantalı Kablo Uzunluğu : 10 m Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SB-10 22kW Tip 2 Soketli 10m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519313-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519314-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519315-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519316-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519317-11-O.jpg"],"description":"Hims 22kW Destekli 10m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 10m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 10m Araç Şarj KablosuHims markasının ürettiği 10m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.10 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imper…',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '10 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Rengi': 'Siyah',
      'Aksesuar': 'Çantalı',
      'Kablo Uzunluğu': '10 m'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-sb-10-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-sb-10-cnt-1.jpg',
      '/images/products/hims-emef-22t2-sb-10-cnt-2.jpg',
      '/images/products/hims-emef-22t2-sb-10-cnt-3.jpg',
      '/images/products/hims-emef-22t2-sb-10-cnt-4.jpg',
      '/images/products/hims-emef-22t2-sb-10-cnt-5.jpg',
      '/images/products/hims-emef-22t2-sb-10-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SB-10-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  },
  {
    id: 'hims-emef-22t2-sb-3-cnt',
    sku: 'EMEF-22T2-SB-3-CNT',
    name: 'Hims EMEF-22T2-SB-3 22kW Tip 2 Soketli 3m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 3m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 3m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 3m Araç Şarj Kablosu Hims markasının ürettiği 3m el',
    fullDescription: 'Hims 22kW Destekli 3m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 3m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 3m Araç Şarj Kablosu Hims markasının ürettiği 3m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 3 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 3 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Rengi : Siyah Aksesuar : Çantalı Kablo Uzunluğu : 3 m Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SB-3 22kW Tip 2 Soketli 3m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519323-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519324-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519325-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519326-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519327-11-O.jpg"],"description":"Hims 22kW Destekli 3m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 3m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 3m Araç Şarj KablosuHims markasının ürettiği 3m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.3 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak …',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '3 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Rengi': 'Siyah',
      'Aksesuar': 'Çantalı',
      'Kablo Uzunluğu': '3 m'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-sb-3-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-sb-3-cnt-1.jpg',
      '/images/products/hims-emef-22t2-sb-3-cnt-2.jpg',
      '/images/products/hims-emef-22t2-sb-3-cnt-3.jpg',
      '/images/products/hims-emef-22t2-sb-3-cnt-4.jpg',
      '/images/products/hims-emef-22t2-sb-3-cnt-5.jpg',
      '/images/products/hims-emef-22t2-sb-3-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SB-3-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  },
  {
    id: 'hims-emef-22t2-sb-7-cnt',
    sku: 'EMEF-22T2-SB-7-CNT',
    name: 'Hims EMEF-22T2-SB-7 22kW Tip 2 Soketli 7m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 7m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 7m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 7m Araç Şarj Kablosu Hims markasının ürettiği 7m el',
    fullDescription: 'Hims 22kW Destekli 7m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 7m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 7m Araç Şarj Kablosu Hims markasının ürettiği 7m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 7 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 7 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Rengi : Siyah Aksesuar : Çantalı Kablo Uzunluğu : 7 m Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SB-7 22kW Tip 2 Soketli 7m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519318-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519319-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519320-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519321-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-sb-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519322-11-O.jpg"],"description":"Hims 22kW Destekli 7m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 7m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 7m Araç Şarj KablosuHims markasının ürettiği 7m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.7 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak …',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '7 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Rengi': 'Siyah',
      'Aksesuar': 'Çantalı',
      'Kablo Uzunluğu': '7 m'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-sb-7-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-sb-7-cnt-1.jpg',
      '/images/products/hims-emef-22t2-sb-7-cnt-2.jpg',
      '/images/products/hims-emef-22t2-sb-7-cnt-3.jpg',
      '/images/products/hims-emef-22t2-sb-7-cnt-4.jpg',
      '/images/products/hims-emef-22t2-sb-7-cnt-5.jpg',
      '/images/products/hims-emef-22t2-sb-7-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SB-7-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  },
  {
    id: 'hims-emef-22t2-ss-10-cnt',
    sku: 'EMEF-22T2-SS-10-CNT',
    name: 'Hims EMEF-22T2-SS-10 22kW Tip 2 Soketli 10m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 10m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 10m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 5m Araç Şarj Kablosu Hims markasının ürettiği 10m',
    fullDescription: 'Hims 22kW Destekli 10m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 10m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 5m Araç Şarj Kablosu Hims markasının ürettiği 10m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 10 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 10 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Rengi : Siyah Aksesuar : Çantalı Kablo Uzunluğu : 10 m Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SS-10 22kW Tip 2 Soketli 10m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519298-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519299-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519300-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519301-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-10-22kw-tip-2-soketli-10m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519302-11-O.jpg"],"description":"Hims 22kW Destekli 10m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 10m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 5m Araç Şarj KablosuHims markasının ürettiği 10m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.10 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imperte…',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '10 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Rengi': 'Siyah',
      'Aksesuar': 'Çantalı',
      'Kablo Uzunluğu': '10 m'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-ss-10-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-ss-10-cnt-1.jpg',
      '/images/products/hims-emef-22t2-ss-10-cnt-2.jpg',
      '/images/products/hims-emef-22t2-ss-10-cnt-3.jpg',
      '/images/products/hims-emef-22t2-ss-10-cnt-4.jpg',
      '/images/products/hims-emef-22t2-ss-10-cnt-5.jpg',
      '/images/products/hims-emef-22t2-ss-10-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SS-10-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  },
  {
    id: 'hims-emef-22t2-ss-3-cnt',
    sku: 'EMEF-22T2-SS-3-CNT',
    name: 'Hims EMEF-22T2-SS-3 22kW Tip 2 Soketli 3m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 3m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 3m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 3m Araç Şarj Kablosu Hims markasının ürettiği 3m el',
    fullDescription: 'Hims 22kW Destekli 3m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 3m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 3m Araç Şarj Kablosu Hims markasının ürettiği 3m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 3 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 3 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Rengi : Siyah Aksesuar : Çantalı Kablo Uzunluğu : 3 m Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SS-3 22kW Tip 2 Soketli 3m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519308-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519309-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519310-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519311-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-3-22kw-tip-2-soketli-3m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519312-11-O.jpg"],"description":"Hims 22kW Destekli 3m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 3m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 3m Araç Şarj KablosuHims markasının ürettiği 3m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.3 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak …',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '3 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Rengi': 'Siyah',
      'Aksesuar': 'Çantalı',
      'Kablo Uzunluğu': '3 m'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-ss-3-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-ss-3-cnt-1.jpg',
      '/images/products/hims-emef-22t2-ss-3-cnt-2.jpg',
      '/images/products/hims-emef-22t2-ss-3-cnt-3.jpg',
      '/images/products/hims-emef-22t2-ss-3-cnt-4.jpg',
      '/images/products/hims-emef-22t2-ss-3-cnt-5.jpg',
      '/images/products/hims-emef-22t2-ss-3-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SS-3-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  },
  {
    id: 'hims-emef-22t2-ss-5-cnt',
    sku: 'EMEF-22T2-SS-5-CNT',
    name: 'Hims EMEF-22T2-SS-5 22kW Tip 2 Soketli 5m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 5m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 5m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 5m Araç Şarj Kablosu Hims markasının ürettiği 5m el',
    fullDescription: 'Hims 22kW Destekli 5m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 5m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 5m Araç Şarj Kablosu Hims markasının ürettiği 5m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 5 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 5 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Uzunluğu : 5 m Aksesuar : Çantalı Kablo Rengi : Siyah Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SS-5 22kW Tip 2 Soketli 5m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-5-22kw-tip-2-soketli-5m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-518429-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-5-22kw-tip-2-soketli-5m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-518433-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-5-22kw-tip-2-soketli-5m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-518432-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-5-22kw-tip-2-soketli-5m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-518430-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-5-22kw-tip-2-soketli-5m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-518431-11-O.jpg"],"description":"Hims 22kW Destekli 5m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 5m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 5m Araç Şarj KablosuHims markasının ürettiği 5m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.5 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak …',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '5 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Uzunluğu': '5 m',
      'Aksesuar': 'Çantalı',
      'Kablo Rengi': 'Siyah'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-ss-5-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-ss-5-cnt-1.jpg',
      '/images/products/hims-emef-22t2-ss-5-cnt-2.jpg',
      '/images/products/hims-emef-22t2-ss-5-cnt-3.jpg',
      '/images/products/hims-emef-22t2-ss-5-cnt-4.jpg',
      '/images/products/hims-emef-22t2-ss-5-cnt-5.jpg',
      '/images/products/hims-emef-22t2-ss-5-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SS-5-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  },
  {
    id: 'hims-emef-22t2-ss-7-cnt',
    sku: 'EMEF-22T2-SS-7-CNT',
    name: 'Hims EMEF-22T2-SS-7 22kW Tip 2 Soketli 7m Çantalı Elektrikli Araç Şarj Kablosu',
    description: 'Hims 22kW Destekli 7m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 7m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 7m Araç Şarj Kablosu Hims markasının ürettiği 7m el',
    fullDescription: 'Hims 22kW Destekli 7m Çantalı Elektrikli Araç Şarj Kablosu Not: Ürün paket içeriğinde 7m şarj kablosu ve şarj kablo çantası bulunmaktadır. Hims 22kW 7m Araç Şarj Kablosu Hims markasının ürettiği 7m elektrikli araç şarj kablosu , aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar. 7 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar. 22kW gücündeki şarj kablosu , Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır. Esnek ve düz yapısı sayesinde kolay taşınabilir. Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur. Hims Araç Şarj Kablo Çantası Hims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır. ✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar. ✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz. Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak üretilmiştir. Bu kumaş, su geçirmez özellikte olup, aynı zamanda sıvıyı emmeyerek içerideki kabloların kuru kalmasını sağlar. ✓ Günlük kullanımda suya, neme ve kire karşı üstün koruma sunar. Araç şarj kablolarınızı taşırken, çarpmalara, sıkışmalara ve dış etkenlere karşı güvenli bir şekilde muhafaza edebilirsiniz. ✓ Eva hardcase olması sayesinde kablo çantası, suya dayanıklı fermuar sistemine sahiptir. Böylece ani yağmurlarda veya nemli ortamlarda bile kablolarınızı güvenle koruyabilirsiniz. ✓ 40 x 40 x 10 cm ölçülerinde olan bu taşıma çantası, 2, 3, 5, 7, 8 ve 10 metre uzunluğundaki kablolar için uygundur. İç bölme düzeni, kabloların içerde sallanmadan taşınmasını sağlar. ✓ Çanta içerisinde kablolarınızın sabit kalmasını sağlayan özel askılar bulunur. Bu sayede kablolarınız hareket etmeyecek ve düzenli bir şekilde yerleştirilecektir. Ergonomik ve sağlam taşıma kulpları, çantayı kolay bir şekilde taşımanıza olanak tanır. Siyah renkli sade ama modern tasarımıyla hem profesyonel kullanımlara hem de günlük ihtiyaçlara uygun bir çantadır. Araç bagajında, garajda veya iş yerinde rahatça saklanabilir. Bu su geçirmez elektrikli araba şarj kablo taşıma çantası, kablolarınızı düzenli, güvenli ve uzun ömürlü bir şekilde saklamak için en ideal üründür. Şık tasarımı, dayanıklı Imperteks kumaşı ve üstün koruma özellikleriyle günlük hayatta vazgeçilmez bir yardımcıdır. Not: Hims markasının şarj kablosu garantisi, teslim edildikten sonra başlar ve 2 yıl geçerlidir. Ürünün bütün parçaları dahil olmak üzere tamamı garanti kapsamındadır. Garanti kapsamında işçilik ve üretim hatalarına karşı garanti mevcuttur. Geleceğin enerjisine yatırım yapmaya hazır mısınız? Elektrikli araç altyapısına yaptığınız yatırımla hem çevreyi koruyun hem de büyüyen bir pazarda yerinizi alın. Bayilik programımız için tıklayın , yerli üretimimiz olan şarj istasyonu ve kabloları ile geleceğin dönüşümüne ortak olun! Şarj Kablosu Özellikleri Çalışma Akımı : 32A Güç Aktarım Kapasitesi : 22 kW Çalıma Gerilimi : 380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.) Çalışma Frekansı : 50/60 Hz Çalışma Sıcaklığı : -25 ile 55 derece Nem : %95\'e kadar yoğuşmasız Kontak Kaplama : Gümüş İletken : %100 Bakır Depolama Sıcaklığı : -30 ile 80 derece Ürün Kablo Uzunluğu : 7 metre Ürün Kablo Kesiti : 5x6 Çanta Özellikleri Ölçü : 40x40x10 cm Kumaş Tipi : Su geçirmez Imperteks kumaş Teknik Özellikler Kablo Rengi : Siyah Aksesuar : Çantalı Kablo Uzunluğu : 7 m Ortalama Puan ★★★★★ Çok İyi ★★★★ ★ İyi ★★★ ★★ Ortalama ★★ ★★★ Kötü ★ ★★★★ Çok Kötü ( ) ( ) ( ) ( ) ( ) {"@context":"https:\\/\\/ ","@type":"Product","name":"Hims EMEF-22T2-SS-7 22kW Tip 2 Soketli 7m Çantalı Elektrikli Araç Şarj Kablosu","image":["https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519303-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519304-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519305-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519306-11-O.jpg","https:\\/\\/www.elektromarketim.com\\/hims-emef-22t2-ss-7-22kw-tip-2-soketli-7m-cantali-elektrikli-arac-sarj-kablosu-elektrikli-arac-sarj-kablolari-hims-519307-11-O.jpg"],"description":"Hims 22kW Destekli 7m Çantalı Elektrikli Araç Şarj KablosuNot: Ürün paket içeriğinde 7m şarj kablosu ve şarj kablo çantası bulunmaktadır.Hims 22kW 7m Araç Şarj KablosuHims markasının ürettiği 7m elektrikli araç şarj kablosu, aracınızı güvenli ve verimli bir şekilde şarj etmenizi sağlar.7 metre uzunluğundaki Hims elektrikli araç şarj kablosu, tüm şarj istasyonlarıyla uyumludur ve sorunsuz kullanım sunar.22kW gücündeki şarj kablosu, Avrupa ve Türkiye’deki tüm Tip 2 soketlere uygun olarak tasarlanmıştır.Esnek ve düz yapısı sayesinde kolay taşınabilir.Yüksek akım taşıyabilen gümüş kontaklı bağlantı uçları, üstün iletkenlik sağlayarak ısınmayı önler ve hem şarj cihazının hem de aracınızın güvenliğini maksimum seviyede korur.Hims Araç Şarj Kablo ÇantasıHims elektrikli araç şarj kablo taşıma çantası, araç şarj kablolarınızı düzenli ve güvenli bir şekilde saklamanız için tasarlanmıştır.✓ Sıvıya dayanıklı yapısı, darbelere karşı ekstra koruma sağlaması ve ergonomik taşıma detaylarıyla günlük kullanımda büyük bir avantaj sunar.✓ Özel Imperteks kumaş kaplaması sayesinde hem sağlam hem de estetik bir ürüne sahip olabilirsiniz.Hims araç şarj kablo çantası, yüksek kaliteli Imperteks kumaş kullanılarak …',
    specifications: {
      'Çalışma Akımı': '32A',
      'Güç Aktarım Kapasitesi': '22 kW',
      'Çalıma Gerilimi': '380V AC ( Trifaze ) (Trifaze kablolar, Monofaze sistemlerde kullanım için uygundur.)',
      'Çalışma Frekansı': '50/60 Hz',
      'Çalışma Sıcaklığı': '-25 ile 55 derece',
      'Nem': '%95\'e kadar yoğuşmasız',
      'Kontak Kaplama': 'Gümüş',
      'İletken': '%100 Bakır',
      'Depolama Sıcaklığı': '-30 ile 80 derece',
      'Ürün Kablo Uzunluğu': '7 metre',
      'Ürün Kablo Kesiti': '5x6',
      'Ölçü': '40x40x10 cm',
      'Kumaş Tipi': 'Su geçirmez Imperteks kumaş',
      'Kablo Rengi': 'Siyah',
      'Aksesuar': 'Çantalı',
      'Kablo Uzunluğu': '7 m'
    },
    features: [],
    image: '/images/products/hims-emef-22t2-ss-7-cnt-1.jpg',
    images: [
      '/images/products/hims-emef-22t2-ss-7-cnt-1.jpg',
      '/images/products/hims-emef-22t2-ss-7-cnt-2.jpg',
      '/images/products/hims-emef-22t2-ss-7-cnt-3.jpg',
      '/images/products/hims-emef-22t2-ss-7-cnt-4.jpg',
      '/images/products/hims-emef-22t2-ss-7-cnt-5.jpg',
      '/images/products/hims-emef-22t2-ss-7-cnt-6.png'
    ],
    productFamilyKey: 'EMEF-22T2-SS-7-CNT',
    price: 0,
    category: 'Elektrikli Araç Şarj ve V2L',
    stock: 0,
    featured: false,
    isVariantProduct: false,
  }
]
